### ISSUE TITLE
Preprocessor issue

### ISSUE THREAD

**Issue by matt-curtis** [logancollins/Mocha#31]
The CocoaScript preprocessor sometimes incorrectly parses brackets. For example, and error is thrown on `items[itemNames[i]]`. Probably because it becomes `items.itemsNames([i])` or somesuch?

**Comment by afedor** [comment]
Is this a CocoaScript issue or a Mocha issue?

**Comment by ccgus** [comment]
It's a cocoa script issue.  So, wrong project.

**Comment by matt-curtis** [comment]
I'll close this and open there
