### ISSUE TITLE
 (BOOL)loadFrameworkWithName:(NSString *)frameworkName not working on yosemite

### ISSUE THREAD

**Issue by maxingchi** [logancollins/Mocha#32]
MochaRunTime Class

`- (BOOL)loadFrameworkWithName:(NSString *)frameworkName`

always return `No` on Mac OS Yosemite

I made a demo,

     void *address = dlopen([libPath UTF8String], RTLD_LAZY);
     if (!address) {
        //NSLog(@"ERROR: Could not load framework dylib: %@, %@", frameworkName, libPath);
        return NO;
     }

the address is null

it works for EL Capitan

**Comment by ccgus** [comment]
What framework are you trying to load?

**Comment by maxingchi** [comment]
thanks,you are write

I found the problem.something is wrong with the custom framwork.
